drop table "SCOTT"."A2_ORDER" cascade constraints;
drop table "SCOTT"."A2_ORDER_PRODUCT" cascade constraints; 
drop table "SCOTT"."A2_CART" cascade constraints; 
drop table "SCOTT"."A2_USER" cascade constraints; 
drop table "SCOTT"."A2_PRODUCT" cascade constraints; 


drop sequence "SCOTT"."USER_ID_SQ";
drop sequence "SCOTT"."CART_ID_SQ";
drop sequence "SCOTT"."PRODUCT_ID_SQ";
drop sequence "SCOTT"."ORDER_PRODUCT_ID_SQ";
drop sequence "SCOTT"."ORDER_ID_SQ";

CREATE TABLE A2_USER 
(
  USER_ID NUMBER(10) NOT NULL 
, USERNAME VARCHAR2(20) 
, PASSWORD VARCHAR2(20)
, FULLNAME VARCHAR2(50)
, ADDRESS VARCHAR2(50) 
, ADMIN NUMBER(1) 
, CONSTRAINT A2_USER_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);


CREATE TABLE A2_CART 
(
  CART_ID NUMBER(10) NOT NULL 
, USER_ID NUMBER(10) 
, CART_TIMESTAMP TIMESTAMP 
, CONSTRAINT CART_PK PRIMARY KEY 
  (
    CART_ID 
  ),
		constraint CART_USER_ID foreign key("USER_ID") references "A2_USER"("USER_ID")
  ENABLE 
);


CREATE TABLE A2_PRODUCT 
(
  PRODUCT_ID NUMBER(10) NOT NULL 
, DESCRIPTION VARCHAR2(200) 
, QUANTITY NUMBER(10) 
, PRICE NUMBER(10, 2) 
, CONSTRAINT PRODUCT_PK PRIMARY KEY 
  (
    PRODUCT_ID 
  )
  ENABLE 
);

CREATE TABLE A2_ORDER 
(
  ORDER_ID NUMBER(10) NOT NULL 
, USER_ID NUMBER(10)  
, CONSTRAINT ORDER_PK PRIMARY KEY 
  (
    ORDER_ID 
  ), 
	constraint A2_ORDER_USER_ID_FK foreign key("USER_ID") references "A2_USER"("USER_ID")
  ENABLE 
);

CREATE TABLE A2_ORDER_PRODUCT 
(
  ORDER_PRODUCT_ID NUMBER(10) NOT NULL 
, USER_ID NUMBER(10) 
, CART_ID NUMBER(10) 
, ORDER_ID NUMBER(10) 
, PRODUCT_ID NUMBER(10) 
, ORDERED_QUANTITY NUMBER(10)  
, CONSTRAINT ORDER_PRODUCT_PK PRIMARY KEY 
  (
    ORDER_PRODUCT_ID 
  ),  
	constraint ORDER_PRODUCT_CART_ID foreign key("CART_ID") references "A2_CART"("CART_ID"), 
	constraint ORDER_PRODUCT_PRODUCT_ID foreign key("PRODUCT_ID") references "A2_PRODUCT"("PRODUCT_ID"),
	constraint ORDER_PRODUCT_ORDER_ID foreign key("ORDER_ID") references "A2_ORDER"("ORDER_ID"),					constraint ORDER_PRODUCT_USER_ID foreign key("USER_ID") references "A2_USER"("USER_ID")		
  ENABLE 
);



CREATE SEQUENCE USER_ID_SQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CART_ID_SQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE PRODUCT_ID_SQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE ORDER_PRODUCT_ID_SQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE ORDER_ID_SQ INCREMENT BY 1 START WITH 1;


CREATE OR REPLACE TRIGGER USER_ID_pk_increment 
    BEFORE INSERT ON A2_USER
    FOR EACH ROW 
    WHEN (NEW.USER_ID IS NULL) 
BEGIN
    SELECT USER_ID_SQ.nextval 
    INTO :new.USER_ID FROM dual;
END;
/
CREATE OR REPLACE TRIGGER CART_ID_pk_increment 
    BEFORE INSERT ON A2_CART
    FOR EACH ROW 
    WHEN (NEW.CART_ID IS NULL) 
BEGIN
    SELECT CART_ID_SQ.nextval 
    INTO :new.CART_ID FROM dual;
END;
/
CREATE OR REPLACE TRIGGER PRODUCT_ID_pk_increment 
    BEFORE INSERT ON A2_PRODUCT
    FOR EACH ROW 
    WHEN (NEW.PRODUCT_ID IS NULL) 
BEGIN
    SELECT PRODUCT_ID_SQ.nextval 
    INTO :new.PRODUCT_ID FROM dual;
END;
/
CREATE OR REPLACE TRIGGER ORDER_PRODUCT_ID_pk_increment 
    BEFORE INSERT ON A2_ORDER_PRODUCT
    FOR EACH ROW 
    WHEN (NEW.PRODUCT_ID IS NULL) 
BEGIN
    SELECT ORDER_PRODUCT_ID_SQ.nextval 
    INTO :new.PRODUCT_ID FROM dual;
END;
/
CREATE OR REPLACE TRIGGER ORDER_ID_pk_increment 
    BEFORE INSERT ON A2_ORDER
    FOR EACH ROW 
    WHEN (NEW.ORDER_ID IS NULL) 
BEGIN
    SELECT ORDER_ID_SQ.nextval 
    INTO :new.ORDER_ID FROM dual;
END;
/

INSERT INTO A2_USER(USERNAME, PASSWORD, FULLNAME, ADDRESS, ADMIN)
VALUES('admin', 'admin', 'Victor Hilotii', 'Pierre-Gadois', 1);

INSERT INTO A2_USER(USERNAME, PASSWORD, FULLNAME, ADDRESS)
VALUES('user', 'user', 'John Smith', 'Sainte-Catherine');

INSERT INTO a2_product(description, quantity, price)
    VALUES('HP Envy', 12, 850.99);
INSERT INTO a2_product(description, quantity, price)
    VALUES('DELL XPS', 8, 900.99);
INSERT INTO a2_product(description, quantity, price)
    VALUES('MacBook Pro', 11, 1719.99);
INSERT INTO a2_product(description, quantity, price)
    VALUES('Acer Aspire', 15, 659.79);
INSERT INTO a2_product(description, quantity, price)
    VALUES('MacBook Air', 15, 1229.79);
INSERT INTO a2_product(description, quantity, price)
    VALUES('ASUS G550JK', 12, 1659.79);

COMMIT;


/

ALTER TABLE A2_ORDER_PRODUCT disable CONSTRAINT ORDER_PRODUCT_PRODUCT_ID;